name: blog

services:
  hugo:
    image: hugomods/hugo:exts-non-root
    command: hugo --cleanDestinationDir --destination /usr/share/nginx/html --baseURL https://blog.barbetta.me
    volumes:
      - .:/src
      - ./public:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      proxy_network:
        ipv4_address: 192.168.100.3  # Static IP for Hugo

  nginx:
    image: nginx:latest
    depends_on:
      - hugo
    networks:
      proxy_network:
        ipv4_address: 192.168.100.4  # Static IP for Blog Nginx
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 1313:80
    restart: unless-stopped

networks:
  proxy_network:
    external: true  # Use the pre-defined network from NPM
