name: Build and Deploy Hugo Site

on:
  # Run on releases
  release:
    types: [published]
  
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build and deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Create pages branch
        run: |
          # Create or reset the pages branch
          if git show-ref --verify --quiet refs/remotes/origin/pages; then
            git checkout -B pages origin/pages
          else
            git checkout --orphan pages
          fi
          
          # Remove all files except .git
          git rm -rf . || true
      
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "https://sbarbett.github.io/reticulating-splines/"
      
      - name: Deploy to pages branch
        run: |
          # Move all contents from public directory to root
          mv public/* .
          mv public/.* . 2>/dev/null || true
          rmdir public
          
          # Add CNAME file for custom domain
          # echo "blog.barbetta.me" > CNAME
          
          # Add all files
          git add .
          
          # Commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Deploy Hugo site - $(date)"
            git push origin pages --force
          fi 